[source]
paths = ["src", "tests"]

[formatter]
# https://docs.rs/mago-formatter/latest/mago-formatter/settings/struct.FormatSettings.html
print-width = 80
trailing-comma = false
null-type-hint = "Question"
parentheses-around-new-in-member-access = true
