# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.allow_nonadmins: "%env(bool:ALLOW_NONADMINS)%"
    app.allow_list: "%env(csv:ALLOW_LIST)%"
    app.game_version: "%env(string:GAME_VERSION)%"
    app.feedback_uri: "%env(string:default::FEEDBACK_URI)%"
    app.analytics_script: "%env(string:default::ANALYTICS_SCRIPT)%"
    app.election_officers: "%env(csv:ELECTION_OFFICERS)%"
    app.icon_dir: "%env(APP_ICON_DIR)%"
    app.map_depot_dir: "%env(APP_MAP_DEPOT_DIR)%"
    app.output_dir: "%env(APP_OUTPUT_DIR)%"
    app.badger_resources: "%env(APP_BADGER_RESOURCES)%"
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $allowNonAdmins: "%app.allow_nonadmins%"
            $allowList: "%app.allow_list%"
            $gameVersion: "%app.game_version%"
            $garageFilesystem: "@oneup_flysystem.statbus.garageFilesystem_filesystem"
            $electionOfficers: "%app.election_officers%"
            $iconDir: "%app.icon_dir%"
            $outputDir: "%app.output_dir%"
            $mapDepotDir: "%app.map_depot_dir%"
            $badgerResources: "%app.badger_resources%"
            array $statbusFeatures: "%statbus%"
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"
    App\Repository\StatbusRepository:
        arguments:
            $statbusConnection: "@doctrine.dbal.statbus_connection"
    twig.markdown.league_common_mark_converter_factory:
        class: App\Twig\LeagueCommonMarkConverterFactory
        arguments:
            - !tagged_iterator twig.markdown.league_extension
    App\Service\TGDB\FeedbackLinkService:
        arguments:
            $feedbackUri: "%app.feedback_uri%"
    App\Factory\SpeciesFactory: ~
    App\Form\BadgerType:
        arguments:
            $speciesClassRegistry: '@App\Service\Species\SpeciesClassRegistry'
            $iconListService: '@App\Service\Icons\IconListService'
            $speciesFactory: '@App\Factory\SpeciesFactory'
